### PR TITLE
Merge upstream

### PR DESCRIPTION
**Pull request by QuentinBisson**
#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

#### Checklist

- [ ] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] Title of the PR starts with chart name (e.g. `[prometheus-couchdb-exporter]`)

### CODE REVIEW

**Comment by QuentinBisson** [comment]
Needed so we can merge https://github.com/giantswarm/cluster-api-monitoring-app into KSM

**Comment by hervenicol** [comment]
Where are we using these charts / which charts do we use? (so we know what to check during the review).

IIUC this is not used for https://github.com/giantswarm/prometheus-operator-app/ for instance?

**Comment by QuentinBisson** [comment]
We use this repo for node-exporter, kube-state-metrics (we need version 2.6.0) and prometheus operator

**Comment by hervenicol** [comment]
I don't believe you for `prometheus-operator` :rofl: 
The upgrade process seems to retrieve from upstream here: https://github.com/prometheus-community/helm-charts.git
 (seen here: https://github.com/giantswarm/prometheus-operator-app/blob/master/script/sync_chart.sh)

**Comment by QuentinBisson** [comment]
That's the old upgrade process :D

**Review by hervenicol — APPROVED** [review]
No big changes from a helm point of view on `node-exporter` and `kube-state-metrics`, LGTM.
Anyway the potentially breaking changes would be in the apps, not in the charts :shrug:

**Comment by QuentinBisson** [comment]
🙇🏻‍♂️

**Pull request merged**
